# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0c\x61pi.academia\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"4\n\x12TokenLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"|\n\rLoginResponse\x12\x33\n\x07success\x18\x01 \x01(\x0b\x32 .api.academia.TokenLoginResponseH\x00\x12,\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1b.api.academia.ErrorResponseH\x00\x42\x08\n\x06result\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\":\n\nTokenValid\x12 \n\x04role\x18\x01 \x01(\x0e\x32\x12.api.academia.Role\x12\n\n\x02id\x18\x02 \x01(\t\"y\n\x12TokenValidResponse\x12+\n\x07success\x18\x01 \x01(\x0b\x32\x18.api.academia.TokenValidH\x00\x12,\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1b.api.academia.ErrorResponseH\x00\x42\x08\n\x06result\"d\n\x17InvalidateTokenResponse\x12\x11\n\x07success\x18\x01 \x01(\tH\x00\x12,\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1b.api.academia.ErrorResponseH\x00\x42\x08\n\x06result\"3\n\rErrorResponse\x12\x11\n\texception\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t*:\n\x04Role\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x41\x44MIN\x10\x01\x12\x0b\n\x07STUDENT\x10\x02\x12\r\n\tPROFESSOR\x10\x03\x32\xf4\x01\n\x0b\x41uthService\x12@\n\x05Login\x12\x1a.api.academia.LoginRequest\x1a\x1b.api.academia.LoginResponse\x12M\n\rValidateToken\x12\x1a.api.academia.TokenRequest\x1a .api.academia.TokenValidResponse\x12T\n\x0fInvalidateToken\x12\x1a.api.academia.TokenRequest\x1a%.api.academia.InvalidateTokenResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROLE._serialized_start=629
  _ROLE._serialized_end=687
  _LOGINREQUEST._serialized_start=28
  _LOGINREQUEST._serialized_end=78
  _TOKENLOGINRESPONSE._serialized_start=80
  _TOKENLOGINRESPONSE._serialized_end=132
  _LOGINRESPONSE._serialized_start=134
  _LOGINRESPONSE._serialized_end=258
  _TOKENREQUEST._serialized_start=260
  _TOKENREQUEST._serialized_end=289
  _TOKENVALID._serialized_start=291
  _TOKENVALID._serialized_end=349
  _TOKENVALIDRESPONSE._serialized_start=351
  _TOKENVALIDRESPONSE._serialized_end=472
  _INVALIDATETOKENRESPONSE._serialized_start=474
  _INVALIDATETOKENRESPONSE._serialized_end=574
  _ERRORRESPONSE._serialized_start=576
  _ERRORRESPONSE._serialized_end=627
  _AUTHSERVICE._serialized_start=690
  _AUTHSERVICE._serialized_end=934
# @@protoc_insertion_point(module_scope)
