services:
  auth-db:
    build:
      context: auth-database
    ports:
      - '3307:3306'
    volumes:
      - mysql_data_auth:/data/db

  study-db:
    build:
      context: study-database
    ports:
      - '3306:3306'
    volumes:
      - mysql_data_study:/data/db

  lectures-db:
    build:
      context: lectures-database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_lectures:/data/db

volumes:
  mongo_data_lectures:
  mysql_data_auth:
  mysql_data_study: