services:
  academia-fe:
    build:
      context: academia-frontend
    ports:
      - "5173:5173"
    restart: on-failure

  auth-ms:
    build:
      context: auth-microservice
    ports:
      - "50051:50051"
    environment:
      - AUTH_DB_HOST=auth-db
      - AUTH_DB_PORT=3306
      - AUTH_DB_HOST_DB_USER=user
      - AUTH_DB_HOST_DB_PASSWORD=password
    networks:
      - academia
      - auth
    restart: on-failure

  auth-db:
    build:
      context: auth-database
    ports:
      - '3307:3306'
    volumes:
      - mysql_data_auth:/data/db
    networks:
      - auth
    restart: on-failure

  study-ms:
    build:
      context: study-microservice
    ports:
      - "8080:8080"
    environment:
      - STUDY_DB_HOST=study-db
      - STUDY_DB_USER=user
      - STUDY_DB_PASSWORD=password
      - LECTURE_MS_HOST_ADDRESS=http://lecture-ms:8000
      - AUTH_MS_HOSTNAME=auth-ms
    networks:
      - academia
      - study
    restart: on-failure

  study-db:
    build:
      context: study-database
    ports:
      - '3306:3306'
    volumes:
      - mysql_data_study:/data/db
    networks:
      - study
    restart: on-failure

  lecture-ms:
    build:
      context: lectures-microservice
    ports:
      - "8000:8000"
    environment:
      - LECTURES_DB_HOST=lectures-db
      - LECTURES_DB_HOST_DB_USER=user
      - LECTURES_DB_HOST_DB_PASSWORD=password
      - STUDY_MS_HOST_ADDRESS=http://study-ms:8080
      - AUTH_MS_HOSTNAME=auth-ms
    networks:
      - academia
      - lecture
    restart: on-failure

  lectures-db:
    build:
      context: lectures-database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_lectures:/data/db1
    networks:
      - lecture
    restart: on-failure

volumes:
  mongo_data_lectures:
  mysql_data_auth:
  mysql_data_study:

networks:
  academia:
    driver: bridge
  study:
    driver: bridge
  auth:
    driver: bridge
  lecture:
    driver: bridge